$axure.loadCurrentPage({
  "url":"dashboard.html",
  "generationDate":new Date(1390358637774.39),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"724b625baf174dcc8a1d8422839b62bf",
    "type":"Axure:Page",
    "name":"Dashboard",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"bbd580e82cb3456085ca74395aaa466a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":113},
            "size":{
              "width":10,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5a688fef8d840c79a0f4816496cb2c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":310,
                  "y":113},
                "size":{
                  "width":10,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6685aeaa728c432d92664c99190c71d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":257,
              "y":360},
            "size":{
              "width":13,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23cb816ee5064af2933c28011600e98e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":257,
                  "y":360},
                "size":{
                  "width":13,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fe39de29c64643999bb91b9085550c70",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":185,
              "y":143},
            "size":{
              "width":1080,
              "height":948}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd3a211ea9524d52a11fc0a1e9a53aed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":185,
                  "y":143},
                "size":{
                  "width":1080,
                  "height":948}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u4.png"}},
{
          "id":"20e8cfd03fde4bf988f27b49ec6a3d9a",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":225,
              "y":420},
            "size":{
              "width":605,
              "height":60}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Algebra 2 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"algebra_2.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"1b3414678cee43a2b7e36d00c0b58375",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"fca3bcac606d4cacb64ce8b27ec21a08"}]}},
  "masters":{
    "fca3bcac606d4cacb64ce8b27ec21a08":{
      "packageId":"fca3bcac606d4cacb64ce8b27ec21a08",
      "type":"Axure:Master",
      "name":"New Master 1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"1086f798d6e64d2f828f0d782e019361",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":185,
                "y":0},
              "size":{
                "width":1080,
                "height":142}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5674c48d00b448d991ef16bf42304571",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":185,
                    "y":0},
                  "size":{
                    "width":1080,
                    "height":142}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u8.png"}},
{
            "id":"556848ff955546f6bb1ee4a75c851b58",
            "label":"profile dropdown",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":false,
            "style":{
              "location":{
                "x":1120,
                "y":100},
              "size":{
                "width":10,
                "height":10},
              "visible":false},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"afd63f99a1cf40b693054cde14993a5d",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"d4def552704d4554b957b36c0dc42e49",
                    "label":"",
                    "parentDynamicPanel":"556848ff955546f6bb1ee4a75c851b58",
                    "type":"flowShape",
                    "styleType":"flowShape",
                    "visible":true,
                    "style":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF},
                      "size":{
                        "width":150,
                        "height":140},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFF999999}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"d4fcc54378844c868df4c2c1dbff39a0",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"556848ff955546f6bb1ee4a75c851b58",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFFFF},
                          "size":{
                            "width":150,
                            "height":140},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFF999999}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/dashboard/u11.png"}},
{
                    "id":"5eb1d50135b3494fa1ff60736feeb30f",
                    "label":"",
                    "parentDynamicPanel":"556848ff955546f6bb1ee4a75c851b58",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":20,
                        "y":39},
                      "size":{
                        "width":60,
                        "height":15}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"82fcdead1cf94aa28b5515c33cf63e2b",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"556848ff955546f6bb1ee4a75c851b58",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":20,
                            "y":39},
                          "size":{
                            "width":60,
                            "height":15}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"e7cf3bdf24fd483697a6ac42fe2e327d",
                    "label":"",
                    "parentDynamicPanel":"556848ff955546f6bb1ee4a75c851b58",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":20,
                        "y":64},
                      "size":{
                        "width":101,
                        "height":15}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"147aa37e282c4e7daeae0efd0a2226ba",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"556848ff955546f6bb1ee4a75c851b58",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":20,
                            "y":64},
                          "size":{
                            "width":101,
                            "height":15}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"85280726cf3a423e9abe65234cbb11bc",
                    "label":"",
                    "parentDynamicPanel":"556848ff955546f6bb1ee4a75c851b58",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":20,
                        "y":89},
                      "size":{
                        "width":91,
                        "height":15}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"33075c9c3d8b4bdfab08d5e68b935192",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"556848ff955546f6bb1ee4a75c851b58",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":20,
                            "y":89},
                          "size":{
                            "width":91,
                            "height":15}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"e779fec92dc6428fbc02d854b627b2d7",
                    "label":"",
                    "parentDynamicPanel":"556848ff955546f6bb1ee4a75c851b58",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":18,
                        "y":14},
                      "size":{
                        "width":73,
                        "height":15}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"fbd4a3274bf34a3897893a4f8a4a2fbe",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"556848ff955546f6bb1ee4a75c851b58",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":18,
                            "y":14},
                          "size":{
                            "width":73,
                            "height":15}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}}]}]},
{
            "id":"3b3e3d3ab2bc4317bef6836ee7af0d7f",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":1190,
                "y":70},
              "size":{
                "width":50,
                "height":30}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 2<br> (If visibility of profile dropdown equals true)",
                    "isNewIfGroup":false,
                    "condition":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetWidgetVisibility",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["556848ff955546f6bb1ee4a75c851b58"]}]},
                      "rightExpr":{
                        "exprType":"booleanLiteral",
                        "value":true}},
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Hide profile dropdown slide up 500 ms",
                        "objectsToFades":[{
                            "objectPath":["556848ff955546f6bb1ee4a75c851b58"],
                            "fadeInfo":{
                              "fadeType":"hide",
                              "options":{
                                "easing":"slideUp",
                                "duration":500,
                                "showType":"none"}}}]}]},
{
                    "description":"Case 1<br> (Else If visibility of profile dropdown equals false)",
                    "isNewIfGroup":false,
                    "condition":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetWidgetVisibility",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["556848ff955546f6bb1ee4a75c851b58"]}]},
                      "rightExpr":{
                        "exprType":"booleanLiteral",
                        "value":false}},
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Show profile dropdown slide down 500 ms",
                        "objectsToFades":[{
                            "objectPath":["556848ff955546f6bb1ee4a75c851b58"],
                            "fadeInfo":{
                              "fadeType":"show",
                              "options":{
                                "easing":"slideDown",
                                "duration":500,
                                "showType":"none"}}}]}]}]}},
            "tabbable":true}]}}},
  "objectPaths":{
    "bbd580e82cb3456085ca74395aaa466a":{
      "scriptId":"u0"},
    "d5a688fef8d840c79a0f4816496cb2c4":{
      "scriptId":"u1"},
    "6685aeaa728c432d92664c99190c71d4":{
      "scriptId":"u2"},
    "23cb816ee5064af2933c28011600e98e":{
      "scriptId":"u3"},
    "fe39de29c64643999bb91b9085550c70":{
      "scriptId":"u4"},
    "fd3a211ea9524d52a11fc0a1e9a53aed":{
      "scriptId":"u5"},
    "20e8cfd03fde4bf988f27b49ec6a3d9a":{
      "scriptId":"u6"},
    "1b3414678cee43a2b7e36d00c0b58375":{
      "scriptId":"u7",
      "1086f798d6e64d2f828f0d782e019361":{
        "scriptId":"u8"},
      "5674c48d00b448d991ef16bf42304571":{
        "scriptId":"u9"},
      "556848ff955546f6bb1ee4a75c851b58":{
        "scriptId":"u10"},
      "d4def552704d4554b957b36c0dc42e49":{
        "scriptId":"u11"},
      "d4fcc54378844c868df4c2c1dbff39a0":{
        "scriptId":"u12"},
      "5eb1d50135b3494fa1ff60736feeb30f":{
        "scriptId":"u13"},
      "82fcdead1cf94aa28b5515c33cf63e2b":{
        "scriptId":"u14"},
      "e7cf3bdf24fd483697a6ac42fe2e327d":{
        "scriptId":"u15"},
      "147aa37e282c4e7daeae0efd0a2226ba":{
        "scriptId":"u16"},
      "85280726cf3a423e9abe65234cbb11bc":{
        "scriptId":"u17"},
      "33075c9c3d8b4bdfab08d5e68b935192":{
        "scriptId":"u18"},
      "e779fec92dc6428fbc02d854b627b2d7":{
        "scriptId":"u19"},
      "fbd4a3274bf34a3897893a4f8a4a2fbe":{
        "scriptId":"u20"},
      "3b3e3d3ab2bc4317bef6836ee7af0d7f":{
        "scriptId":"u21"}}}});